/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class PersistTest {
    @Test public void persistancetestFormNumber20() {
        int result = Persist.persistence(425);

        assertEquals(2, result);
    }
}